[package]
name = "face-crop-forge"
version = "0.1.0"
edition = "2024"

[dependencies]
leptos = { version = "=0.8.19", features = ["csr"] }
console_error_panic_hook = "=0.1.7"
wasm-bindgen-futures = "=0.4.68"
zip = { version = "=8.5.1", default-features = false, features = ["deflate"] }
serde = { version = "=1.0.228", features = ["derive"] }
serde_json = "=1.0.149"
web-sys = { version = "=0.3.95", features = ["Window", "Document", "Element", "HtmlElement", "HtmlAnchorElement", "Storage", "Url", "HtmlInputElement", "FileList", "File", "FilePropertyBag", "Blob", "BlobPropertyBag", "Worker", "DragEvent", "DataTransfer", "HtmlCanvasElement", "CanvasRenderingContext2d", "HtmlImageElement", "Navigator", "MediaDevices", "MediaDeviceInfo", "MediaStream", "MediaStreamTrack", "MediaStreamConstraints", "HtmlVideoElement", "HtmlMediaElement"] }

[profile.release]
codegen-units = 1
lto = true
opt-level = "z"
panic = "abort"
