[package]
name = "face-crop-forge"
version = "0.3.1"
edition = "2024"

[dependencies]
console_error_panic_hook = "=0.1.7"
js-sys = "=0.3.98"
leptos = { version = "=0.8.19", features = ["csr"] }
serde = { version = "=1.0.228", features = ["derive"] }
serde_json = "=1.0.149"
wasm-bindgen = "=0.2.121"
wasm-bindgen-futures = "=0.4.71"
web-sys = { version = "=0.3.98", features = ["Blob", "BlobPropertyBag", "Clipboard", "console", "CanvasRenderingContext2d", "DataTransfer", "Document", "DragEvent", "Element", "Event", "File", "FileList", "FilePropertyBag", "FileReader", "History", "HtmlAnchorElement", "HtmlCanvasElement", "HtmlCollection", "HtmlElement", "HtmlImageElement", "HtmlInputElement", "HtmlMediaElement", "HtmlVideoElement", "ImageBitmap", "Location", "MediaDeviceInfo", "MediaDevices", "MediaStream", "MediaStreamConstraints", "MediaStreamTrack", "MouseEvent", "Navigator", "Storage", "Url", "Window", "Worker"] }
zip = { version = "=8.6.0", default-features = false, features = ["deflate"] }

[dev-dependencies]
wasm-bindgen-test = "0.3.71"

[profile.release]
codegen-units = 1
lto = true
opt-level = "z"
panic = "abort"
